local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 5.0
  publish_frequency: 1.2
  static_map: false
  rolling_window: true
  max_obstacle_width: 8.0
  max_obstacle_height: 8.0
  width: 3
  height: 3
  resolution: 0.05
  transfrom_tolerance: 1.5
