obstacle_range: 2
raytrace_range: 2.0
footprint: [[0.65,0.5],[-0.65,0.5],[-0.65,-0.5],[0.65,-0.5]]
inflation_radius: 1.75
cost_scaling_factor: 2.58

observation_sources: laser_scan_front laser_scan_back 

laser_scan_front: {sensor_frame: sick_s300_laser_front_link , data_type: LaserScan, topic: sick_s300_laser/front/scan, marking: true, clearing: true}


laser_scan_back: {sensor_frame: sick_s300_laser_back_link , data_type: LaserScan, topic: sick_s300_laser/back/scan, marking: true, clearing: true}



